---
- name: Converge
  hosts: all
  vars:
    nix_flakes: true
    nix_user: molecule
    nix_bind_mount: "/new/nix"

  roles:
    - ableton.nix

  tasks:
    - name: Get list of channels
      become: true
      become_user: "{{ nix_user }}"
      ansible.builtin.command: "nix-channel --list"
      environment:
        PATH: "/home/{{ nix_user }}/.nix-profile/bin:{{ lookup('env', 'PATH') }}"
      register: nix_channels
      changed_when: false

    - name: Add unstable channel
      become: true
      become_user: "{{ nix_user }}"
      ansible.builtin.command: >
        nix-channel --add https://nixos.org/channels/nixpkgs-unstable nixpkgs
      environment:
        PATH: "/home/{{ nix_user }}/.nix-profile/bin:{{ lookup('env', 'PATH') }}"
      changed_when: true
      when: '"nixpkgs https://nixos.org/channels/nixpkgs-unstable" != nix_channels.stdout'

    - name: Update channels
      become: true
      become_user: "{{ nix_user }}"
      ansible.builtin.command: "nix-channel --update"
      environment:
        PATH: "/home/{{ nix_user }}/.nix-profile/bin:{{ lookup('env', 'PATH') }}"
      changed_when: true
      when: '"nixpkgs https://nixos.org/channels/nixpkgs-unstable" != nix_channels.stdout'

    - name: Get list of installed Nix packages
      become: true
      become_user: "{{ nix_user }}"
      ansible.builtin.command: "nix-env --query --installed"
      environment:
        PATH: "/home/{{ nix_user }}/.nix-profile/bin:{{ lookup('env', 'PATH') }}"
      changed_when: false
      register: nix_packages

    - name: Try to install a Nix package
      become: true
      become_user: "{{ nix_user }}"
      ansible.builtin.command: "nix-env --install --attr nixpkgs.hello"
      environment:
        PATH: "/home/{{ nix_user }}/.nix-profile/bin:{{ lookup('env', 'PATH') }}"
      when: "'hello' not in nix_packages.stdout"
      changed_when: true

    - name: Try to run the hello Nix package
      become: true
      become_user: "{{ nix_user }}"
      ansible.builtin.command: "hello"
      environment:
        PATH: "/home/{{ nix_user }}/.nix-profile/bin:{{ lookup('env', 'PATH') }}"
      changed_when: false
      register: hello_output

    - name: Verify output of the hello program
      ansible.builtin.fail:
        msg: "The hello program did not return the expected output!"
      when: "hello_output.stdout != 'Hello, world!'"

    - name: Try to use Nix Flakes
      become: true
      become_user: "{{ nix_user }}"
      ansible.builtin.command: "nix flake metadata github:edolstra/dwarffs"
      environment:
        PATH: "/home/{{ nix_user }}/.nix-profile/bin:{{ lookup('env', 'PATH') }}"
      changed_when: false
