---
- name: Converge
  hosts: all
  vars:
    nix_flakes: true
    nix_user: molecule
    nix_bind_mount: "/new/nix"

  roles:
    - ansible-role-nix

  tasks:
    - name: Get list of installed Nix packages
      become: true
      become_flags: "--login"
      become_user: "{{ nix_user }}"
      shell: "nix-env --query --installed"
      changed_when: false
      register: nix_packages

    - name: Try to install a Nix package
      become: true
      become_flags: "--login"
      become_user: "{{ nix_user }}"
      shell: "nix-env -i hello"
      when: "'hello' not in nix_packages.stdout"

    - name: Try to run the hello Nix package
      become: true
      become_flags: "--login"
      become_user: "{{ nix_user }}"
      command: "hello"
      changed_when: false
      register: hello_output

    - name: Verify output of the hello program
      fail:
        msg: "The hello program did not return the expected output!"
      when: "hello_output.stdout != 'Hello, world!'"

    - name: Try to use Nix Flakes
      become: true
      become_flags: "--login"
      become_user: "{{ nix_user }}"
      shell: "nix flake metadata github:edolstra/dwarffs"
      changed_when: false
