{% if item.registry is defined %}
FROM {{ item.registry.url }}/{{ item.image }}
{% else %}
FROM {{ item.image }}
{% endif %}

RUN apt-get update && \
    apt-get install -y ca-certificates curl gnupg python3 python3-apt sudo xz-utils && \
    apt-get clean

RUN useradd -G sudo -m molecule
