---
dependency:
  name: galaxy
  options:
    force: true
driver:
  name: docker
platforms:
  - name: ansible-role-nix-focal
    image: ubuntu:20.04
    privileged: true
  - name: ansible-role-nix-noble
    image: ubuntu:24.04
    privileged: true
provisioner:
  name: ansible
  log: true
verifier:
  name: ansible
